language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
before_deploy:
  - npm install ws browserify@12.0.2 coffeeify@2.0.1
  - mkdir -p deploy/meshblu-midi/latest
  - mkdir -p deploy/meshblu-midi/$TRAVIS_TAG
  - node_modules/.bin/browserify -t coffeeify -s Connector connector.coffee > deploy/meshblu-midi/latest/meshblu-midi.js
  - gzip deploy/meshblu-midi/latest/meshblu-midi.js
  - mv deploy/meshblu-midi/latest/meshblu-midi.js.gz deploy/meshblu-midi/latest/meshblu-midi.js
  - cp deploy/meshblu-midi/latest/meshblu-midi.js deploy/meshblu-midi/$TRAVIS_TAG/meshblu-midi.js
deploy:
  - provider: s3
    region: us-west-2
    skip_cleanup: true
    detect_encoding: true
    access_key_id: replace-me
    secret_access_key:
      secure: replace-me
    bucket: octoblu-cdn
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: replace-me
    api_key:
      secure: replace-me
    on:
      tags: true
      all_branches: true
